name: Professor Sonia Meyer's Website
markdown: kramdown
pygments: true
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME']
title : Professor Sonia Meyer's Website
author :
  name : Sonia Meyer
  email : sonia@meyercraft.net
