name: Sonia's Beihang Website
markdown: kramdown
pygments: true
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME']
title : Sonia's Beihang Website
author :
  name : Sonia Meyer
  email : sonia@meyercraft.net
